source 'https://github.com/CocoaPods/Specs.git'

target 'Avenue', :exclusive => true do
  pod "KVOController", :git => 'https://github.com/dbachrach/KVOController.git'
  pod "Avenue", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "Avenue", :path => "../"

  pod 'Specta', '~> 0.2.1'
  pod 'Expecta'
end
