platform :ios, '8.0'
use_frameworks!

target 'Avenue', :exclusive => true do
  pod "Avenue", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "Avenue", :path => "../"

  pod 'Specta', '~> 0.2.1'
  pod 'Expecta'
end
